### ISSUE TITLE
Example Config Entry seems falsy

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/JMusicBot-archetypes#3]
```java
@JvmOverloads 
public StringEntry(Class<?> $outer,
                   String base,
                   String key,
                   boolean description,
                   String isSecret,
                   <? super , ?, ?> uiNode,
                   com.github.bjoernpetersen.jmusicbot.config.ConfigChecker ui)
```

This is the Javadoc provided for StringEntry. This seems shifted. Also in the example entry
`key` looks like a description, while `isSecret` looks like what should be `base`.
<br>
Provided example:
```java
config.new StringEntry(
        getClass(),
        "example",
        "This is an example config entry",
        false, // not a secret
        "example-default-value",
        new TextBox(),
        value -> {
          // check for valid value
          if (value.contains("example")) {
            return null;
          } else {
            return "Value must contain example";
          }
        }
    );
```

**Comment by FelixGail** [comment]
Shall i also create an issue in JMusicBot, as the first part needs to be fixed there?

**Comment by BjoernPetersen** [comment]
I agree that this is confusing. The first argument is actually falsely added to the JavaDoc because StringEntry is an inner class of Config, so the wrong JavaDoc is Kotlins fault.

The JavaDoc name for the ConfigChecker ("ui") is definitely wrong though.

Just to be sure, the example config entry does compile, right?

### Note: 
If you want to do the same in Kotlin, you can use the named parameter syntax and omit the uiNode parameter, because TextBox is the default for non-secret entries anyway:
```kotlin
exampleEntry = config.StringEntry(
  getClass(),
  "example",
  "This is an example config entry",
  false,
  "example-default-value",
  ui = { if (it.contains("example")) null else "Value must contain example" }
)
```
